### ISSUE TITLE
Compile errors with Swift 4.1.2 and Xcode 9.4.1

### ISSUE THREAD

**Issue by bmorton** [smasher164/swift-cgo-example#1]
I am trying to compile this on 10.13, which with a couple modifications to the makefile seems possible.  These errors I think I've worked around:

* `NSApplication.shared()` seems to not be supported anymore?  I was getting this error, but removing this line of code doesn't seem to break anything yet.
```
minimal.swift:7:29: error: cannot call value of non-function type 'NSApplication'
        NSApplication.shared()
        ~~~~~~~~~~~~~~~~~~~~^~
```

* `'NSTitledWindowMask' is unavailable in Swift`.  Replaced this with `.fullSizeContentView` and it seems to have fixed it.  Here's the error I was getting:
```
minimal.swift:10:42: error: 'NSTitledWindowMask' is unavailable in Swift
                              styleMask: NSTitledWindowMask,
                                         ^~~~~~~~~~~~~~~~~~
AppKit.NSTitledWindowMask:3:12: note: 'NSTitledWindowMask' has been explicitly marked unavailable here
```

I can't seem to get past this part:
```
minimal.m:6:13: warning: class method '+CreateWindow' not found (return type defaults to 'id') [-Wobjc-method-access]
    [Window CreateWindow];
```

Running `minimal.go` exhibits the same issue before crashing:
```
2018-07-26 16:59:58.242 minimal[22059:5510792] +[minimal.Window CreateWindow]: unrecognized selector sent to class 0x40d81a8
2018-07-26 16:59:58.243 minimal[22059:5510792] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[minimal.Window CreateWindow]: unrecognized selector sent to class 0x40d81a8'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3de372db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff64fd8c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3decfcf4 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff3ddad820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff3ddad1e8 _CF_forwarding_prep_0 + 120
	5   minimal.a                           0x00000000040d777e CreateWindow + 30
	6   minimal                             0x0000000004046700 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff65d42b66 m=0 sigcode=0
```

Is there something simple that I'm missing?  I did some Objective C programming ages ago and have dabbled with Swift, but it's been quite some time.

**Comment by bmorton** [comment]
I can't get the window to show up yet, but I've gotten past the `unrecognized selector` error by changing the function definition to:

```
@objc public static func CreateWindow() {
```

**Comment by smasher164** [comment]
I don't have 10.13 running, but I'll take a look at this.
`NSApplication.shared()` is meant to hook into the window server. You can probably replace the code inside `CreateWindow` with anything that opens a window in 10.13 and swift 4.

**Comment by smasher164** [comment]
The latest commit fixes this issue, first by updating its API usage, but primarily by adding the @objc annotation to static methods that need to be exposed.
