### ISSUE TITLE
Could we call a Swift global function from Objective-C?

### ISSUE THREAD

**Issue by wangkuiyi** [smasher164/swift-cgo-example#2]
I tried to Google before asking here. However, Google found some questions without the answer, like [this](https://stackoverflow.com/questions/43638592/how-do-i-expose-a-swift-global-function-to-objective-c?noredirect=1&lq=1) and [this](https://stackoverflow.com/questions/26463487/swift-globals-and-global-functions-in-objective-c).

I tried to add a global function in minimal.swift; however, `swiftc` says 

> `@objc` can only be used with members of classes ...

**Comment by wangkuiyi** [comment]
I got the answer -- it doesn't need to have Objective-C bridging header; instead, Go -> CGO -> Swift.

For the CGO->Swift part, I referred to https://gist.github.com/HiImJulien/c79f07a8a619431b88ea33cca51de787. The Go -> C part is straightforward.

My `a.swift` is as the following

```swift
@_cdecl("greet")
public func greet() {
    print("Hello")
}
```

My `a.go` is

```go
package main
/*
#cgo LDFLAGS: -la -L.
void greet();
*/
import "C"
func main() {
	C.greet()
}
```

To build `a.swift` into a shared library

```bash
swiftc a.swift -emit-library
```

To build, link, and run `a.go`:

```bash
go run a.go
```

**Comment by smasher164** [comment]
I didn't mention @_cdecl since it's an unofficial api. However, if it meets your criteria, use it! :)
